package com.college.gatepass.controller;

import com.college.gatepass.dto.Dtos;
import com.college.gatepass.exception.ApiException;
import com.college.gatepass.service.GatePassService;
import com.college.gatepass.service.QrCodeService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

/**
 * REST endpoints for the security guard's gate-scanning workflow.
 *
 * <p>Two operations are supported:
 * <ol>
 *   <li>GET /api/verify/{qrToken} — preview the pass details before scanning
 *       (read-only, served from Redis cache if available).</li>
 *   <li>POST /api/verify/scan — perform the actual scan to record exit or entry.</li>
 * </ol>
 *
 * <p>The optional {@code exp} and {@code sig} query parameters are validated when
 * present (QR codes generated by the app include them). If they are absent (e.g.
 * a manually typed URL), validation is skipped so guards can look up passes
 * by token directly during testing.
 */
@Tag(name = "Verify / Scan", description = "Security guard QR scanning endpoints")
@RestController
@RequestMapping("/api/verify")
@RequiredArgsConstructor
public class VerifyController {

    private final GatePassService passService;
    private final QrCodeService qrCodeService;

    /**
     * Looks up a gate pass by its QR token and returns its current status.
     * Both {@code exp} and {@code sig} query parameters are REQUIRED.
     * QR codes generated by the app always include them.
     *
     * <p>The HMAC signature is always validated to ensure the QR code was
     * generated by this server, has not been tampered with, and has not expired.
     *
     * @param qrToken the token extracted from the scanned QR code URL path
     * @param exp     expiry timestamp (Unix epoch seconds) — required
     * @param sig     HMAC-SHA256 signature — required
     * @return 200 OK with gate pass details, or 400/403/404 on error
     */
    @Operation(summary = "Preview gate pass details by QR token (read-only)")
    @PreAuthorize("hasAnyRole('SECURITY','ADMIN','WARDEN')")
    @GetMapping("/{qrToken}")
    public ResponseEntity<Dtos.GatePassResponse> verify(
            @PathVariable String qrToken,
            @RequestParam Long exp,
            @RequestParam String sig) {

        // Reject expired links upfront before hitting the database
        if (exp < (System.currentTimeMillis() / 1000)) {
            throw ApiException.badRequest("QR code link has expired. Ask the student to refresh.");
        }

        // Validate HMAC signature — always required in production
        if (!qrCodeService.verifySignedUrl(qrToken, exp, sig)) {
            throw ApiException.forbidden(
                    "QR code signature is invalid. Ask the student to show their QR code again.");
        }

        return ResponseEntity.ok(passService.verifyLookup(qrToken));
    }

    /**
     * Performs an exit or entry scan for the student presenting the QR code.
     *
     * <p>First scan (pass status = APPROVED): marks the student as departed (USED),
     * recording the exit timestamp.
     * Second scan (pass status = USED): marks the student as returned (RETURNED),
     * recording the entry timestamp.
     *
     * <p>If the pass's {@code returnBy} deadline has passed at the time of the
     * first scan, the pass is marked EXPIRED and the call returns a 409 error —
     * the guard can alert the warden about an overdue student.
     *
     * @param securityId the logged-in security guard's user ID (from JWT)
     * @param request    the scan request body containing the QR token string
     * @param httpReq    the HTTP request (used to extract the client IP for audit log)
     * @return 200 OK with the updated gate pass DTO showing the new status
     */
    @Operation(summary = "Perform an exit or entry scan (security guard action)")
    @PreAuthorize("hasAnyRole('SECURITY','ADMIN')")
    @PostMapping("/scan")
    public ResponseEntity<Dtos.GatePassResponse> scan(
            @AuthenticationPrincipal Long securityId,
            @Valid @RequestBody Dtos.ScanRequest request,
            HttpServletRequest httpReq) {

        String ip = resolveIp(httpReq);
        return ResponseEntity.ok(passService.markUsed(request.qrToken(), securityId, ip));
    }

    // ── Private helper ───────────────────────────────────────────────────────

    /**
     * Extracts the real client IP, accounting for reverse-proxy forwarding.
     *
     * @param request the HTTP request
     * @return the real client IP address string
     */
    private String resolveIp(HttpServletRequest request) {
        String forwarded = request.getHeader("X-Forwarded-For");
        return (forwarded != null && !forwarded.isBlank())
                ? forwarded.split(",")[0].strip()
                : request.getRemoteAddr();
    }
}